{
 "title": "Datos Analizador Coras",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "db", "query": "potenciaActiva_value" },
   { "name": "coraid", "query": "potenciaActiva_value" },
   { "name": "circuito", "query": "0,1,2,3F" },
   {
    "name": "metricc",
    "query": "potenciaActiva,corriente,cosenofix,factorpotencia,potenciaaparente,potenciacapacitativa,potenciainductiva,tensionfase"
   }
  ]
 },
 "panels": [
  {
   "title": "Circuit Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coracircuitstatus_value{coraid=~\"$coraid\"}",
     "legendFormat": "C{{circuito}}  ACEnabled:{{astronomicalclockenabled}}"
    }
   ]
  },
  {
   "title": "Comparativa Potencias",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Potencia Activa Actual",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "potenciaActiva_value{coraid=~\"$coraid\"}",
       "legendFormat": "C:{{circuito}}"
      }
     ]
    },
    {
     "title": "Variacion Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "(avg(sum(potenciaActiva_value{coraid=~\"$coraid\"}) - sum(potenciaActiva_value{coraid=~\"$coraid\"} offset 1d))) * ($__range_s/3600)"
      }
     ]
    },
    {
     "title": "Ahorro",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "avg(sum(potenciaActiva_value{coraid=~\"$coraid\"}) - sum(potenciaActiva_value{coraid=~\"$coraid\"} offset 1d)) * ($__range_s/3600) * (-0.1) / 1000"
      }
     ]
    },
    {
     "title": "24 Horas Antes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(potenciaActiva_value{coraid=~\"$coraid\"} offset 1d)",
       "legendFormat": "C: {{circuito}}"
      }
     ]
    },
    {
     "title": "Test",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "WITH (\r\n    corasum= sum(potenciaActiva_value{coraid=~\"$coraid\"}),\n    resu= (avg(corasum) - avg(corasum offset 24h)) * ($__range_s/3600)\n)\r\nresu"
      }
     ]
    },
    {
     "title": "Variacion VS 24 Horas Previas",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "(potenciaActiva_value{coraid=~\"$coraid\"}) - (potenciaActiva_value{coraid=~\"$coraid\"} offset 1d)",
       "legendFormat": "C: {{circuito}}"
      }
     ]
    }
   ]
  },
  { "title": "Explorador Datos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Explorador Datos de Metrica: $metricc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metricc]]_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}"
    }
   ]
  },
  { "title": "Datos Analizador", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "TensionFase : $coraid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "tensionfase_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}/10",
     "legendFormat": "{{coraid}} C:{{circuito}}"
    },
    {
     "expr": "(tensionfase_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}/10) offset 1d",
     "legendFormat": "Dia Previo {{coraid}} C:{{circuito}}"
    }
   ]
  },
  {
   "title": "PotenciaActiva : $coraid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "potenciaActiva_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}",
     "legendFormat": "{{coraid}} C:{{circuito}}"
    },
    {
     "expr": "(potenciaActiva_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}) offset 1d",
     "legendFormat": "DiaPrevio {{coraid}} C:{{circuito}}"
    }
   ]
  },
  {
   "title": "Corriente : $coraid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "expr": "corriente_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}",
     "legendFormat": "{{coraid}} C:{{circuito}}"
    },
    {
     "expr": " (corriente_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}) offset 1d",
     "legendFormat": "DiaPrevio {{coraid}} C:{{circuito}}"
    }
   ]
  }
 ]
}