{
 "title": "Playground Datos",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "query": "potenciaActiva_value" },
   { "name": "coraid", "query": "corriente_value" },
   { "name": "circuito", "query": "0,1,2,3F" }
  ]
 },
 "panels": [
  {
   "title": "Resumen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coras enviando Datos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(potenciaActiva_value[$__interval])/3"
      }
     ]
    },
    {
     "title": "Potencia Total [Actual]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum(potenciaActiva_value[$__interval])"
      }
     ]
    },
    {
     "title": "Potencia Maxima por Circuito [Actual]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "max(potenciaActiva_value[$__interval])"
      }
     ]
    },
    {
     "title": "Potencia Minima por Circuito [Actual]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "min(potenciaActiva_value[$__interval])"
      }
     ]
    },
    {
     "title": "Cambio Maximo Potencia en Circuito",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "max(delta(potenciaActiva_value[$__interval]))"
      }
     ]
    },
    {
     "title": "Potencias Negativas",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "min(potenciaActiva_value<0) by (coraid)"
      }
     ]
    }
   ]
  },
  { "title": "Datos Analizador", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cora Seleccionado => CoraId : $coraid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "potenciaActiva_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}",
     "legendFormat": "PotenciaActiva  Circuito:{{circuito}}"
    }
   ]
  },
  {
   "title": "Prediction-1h Based on last 24h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(potenciaActiva_value{coraid=~\"$coraid\",db=~\"$db\",circuito=~\"$circuito\"}[1d],3600)",
     "legendFormat": "CoraID:{{coraid}} C:{{circuito}}"
    }
   ]
  }
 ]
}