{
 "title": "Resumen Datos Analizador",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Resumen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lecturas de Analizador Recividas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(potenciaActiva_value[$__range]))/3"
    }
   ]
  },
  {
   "title": "Suma Potencia Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Potencia Maxima por Circuito [Actual]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Potencia Minima por Circuito [Actual]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "min(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Cambio Maximo Potencia en Circuito",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(delta(potenciaActiva_value[$__range]))"
    }
   ]
  },
  {
   "title": "Distribucion Potencias",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(2,potenciaActiva_value[$__interval])",
     "legendFormat": "{{coraid}} C: {{circuito}}"
    }
   ]
  }
 ]
}