{
 "title": "2. By Namespace metrics",
 "description": "Displays Namespace utilization",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Project $Namespace Quotas - CPU Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Millicores" }
   ],
   "targets": [
    {
     "aliasBy": "limit_{{resource.label.container_name}}",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_MEAN",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.namespace_name",
      "=~",
      "$Namespace$"
     ],
     "groupBys": [ "resource.label.container_name" ],
     "lastQuery": "aggregation.alignmentPeriod=+60s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.container_name&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"kubernetes.io/container/cpu/limit_utilization\"+resource.label.namespace_name=monitoring.regex.full_match(\"jx-staging$\")&interval.endTime=2019-10-23T11:20:58Z&interval.startTime=2019-10-23T11:05:58Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "kubernetes.io/container/cpu/limit_utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "1",
     "usedAlignmentPeriod": 60,
     "valueType": "DOUBLE"
    },
    {
     "aliasBy": "request_{{resource.label.container_name}}",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_MEAN",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.namespace_name",
      "=~",
      "$Namespace$"
     ],
     "groupBys": [ "resource.label.container_name" ],
     "lastQuery": "aggregation.alignmentPeriod=+60s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.container_name&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"kubernetes.io/container/cpu/request_utilization\"+resource.label.namespace_name=monitoring.regex.full_match(\"jx-staging$\")&interval.endTime=2019-10-23T11:20:55Z&interval.startTime=2019-10-23T11:05:55Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "kubernetes.io/container/cpu/request_utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "1",
     "usedAlignmentPeriod": 60,
     "valueType": "DOUBLE"
    }
   ]
  },
  {
   "title": "Pods CPU usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Project $Namespace Quotas - Memory Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory" }
   ],
   "targets": [
    {
     "aliasBy": "request_{{resource.label.container_name}}",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_MEAN",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.namespace_name",
      "=~",
      "$Namespace$"
     ],
     "groupBys": [ "resource.label.container_name" ],
     "lastQuery": "aggregation.alignmentPeriod=+60s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.container_name&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"kubernetes.io/container/memory/request_utilization\"+resource.label.namespace_name=monitoring.regex.full_match(\"jx-staging$\")&interval.endTime=2019-10-23T11:17:06Z&interval.startTime=2019-10-23T11:02:06Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "kubernetes.io/container/memory/request_utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "1",
     "usedAlignmentPeriod": 60,
     "valueType": "DOUBLE"
    },
    {
     "aliasBy": "limit_{{resource.label.container_name}}",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_MEAN",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.namespace_name",
      "=~",
      "$Namespace$"
     ],
     "groupBys": [ "resource.label.container_name" ],
     "lastQuery": "aggregation.alignmentPeriod=+60s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.container_name&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"kubernetes.io/container/memory/limit_utilization\"+resource.label.namespace_name=monitoring.regex.full_match(\"jx-staging$\")&interval.endTime=2019-10-23T11:17:11Z&interval.startTime=2019-10-23T11:02:11Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "kubernetes.io/container/memory/limit_utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "1",
     "usedAlignmentPeriod": 60,
     "valueType": "DOUBLE"
    }
   ]
  },
  {
   "title": "Total Pods memory usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory " }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"})",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "title": "Total Network I/O pressure for  $Namespace",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
     "legendFormat": "docker: {{ fqdn }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
     "legendFormat": "rkt: {{ fqdn }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$Namespace$\"}) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}) by (fqdn, name, image)",
     "legendFormat": "docker: {{ fqdn }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}) by (fqdn, rkt_container_name)",
     "legendFormat": "rkt: {{ fqdn }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Pods network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod_name)",
     "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod_name)",
     "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
     "legendFormat": "-> docker: {{ fqdn }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
     "legendFormat": "<- docker: {{ fqdn }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
     "legendFormat": "-> rkt: {{ fqdn }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
     "legendFormat": "<- rkt: {{ fqdn }} | {{ rkt_container_name }}"
    }
   ]
  }
 ]
}