{
 "title": "VictoriaMetricsTest",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "query": "potenciaActiva_value" },
   { "name": "coraid", "query": "potenciaActiva_value" },
   { "name": "circuito", "query": "0,1,2" }
  ]
 },
 "panels": [
  {
   "title": "Cora Seleccionado => CoraId : $coraid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "potenciaActiva_value{coraid=\"$coraid\",db=\"$db\",circuito=\"$circuito\"}",
     "legendFormat": "PotenciaActiva  Circuito:{{circuito}}"
    }
   ]
  },
  {
   "title": "Coras enviando Datos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(potenciaActiva_value[$__interval])/3"
    }
   ]
  },
  {
   "title": "Potencia Maxima",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Potencia Minima",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "watt",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Potencia Total Maxima",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(potenciaActiva_value[$__interval])"
    }
   ]
  },
  {
   "title": "Potencia (W)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 2 },
   "targets": [
    { "expr": "potenciaActiva_value > 0", "legendFormat": "Cora:{{coraid}} C:{{circuito}}" }
   ]
  },
  {
   "title": "Todos Coras",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "potenciaActiva_value" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "predict_linear(potenciaActiva_value{coraid=\"$coraid\",circuito=\"$circuito\"}[$__interval],600)"
    }
   ]
  }
 ]
}