{
 "title": "Cora Connection Status EVENTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "coraid",
    "query": "label_values(coraconnectstatus_value, coraid)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cambios Conexiones TODOS Coras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "coraconnectstatus_value", "legendFormat": "{{coraid}}" }
   ]
  },
  {
   "title": "Eventos de desconexion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "(count((coraconnectstatus_value)==0))"
    }
   ]
  },
  {
   "title": "Eventos de conexion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "(count((coraconnectstatus_value)==1))"
    }
   ]
  },
  {
   "title": "Estados Actuales",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "coraconnectstatus_value{coraid=~\"$coraid\"}[$__range]",
     "legendFormat": "{{coraid}}"
    }
   ]
  },
  { "title": "Coras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$coraid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "repeat": "coraid",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coraconnectstatus_value{coraid=~\"$coraid\"}",
     "legendFormat": "Estado"
    }
   ]
  },
  {
   "title": "$coraid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coraconnectstatus_value{coraid=~\"$coraid\"}",
     "legendFormat": "Estado"
    }
   ]
  },
  {
   "title": "$coraid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coraconnectstatus_value{coraid=~\"$coraid\"}",
     "legendFormat": "Estado"
    }
   ]
  }
 ]
}